[package]
name="okv"
version="0.0.2"
edition="2021"
description="A versatile key-value storage library"
keywords=["key-value", "database", "rocksdb", "sqlite", "serde"]
categories=["database", "concurrency", "api-bindings"]
license="MIT OR Apache-2.0"
authors=["Henry Gressmann <mail@henrygressmann.de>"]
repository="https://github.com/explodingcamera/okv"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder="1.5"
thiserror="1.0.50"

rocksdb={version="0.21.0", optional=true, default-features=false, features=["multi-threaded-cf"]}
# rusqlite={version="0.30", optional=true}
dashmap={version="5.5", optional=true}

serde={version="1.0", optional=true, features=["derive"]}
serde_json={version="1.0", optional=true}
rmp-serde={version="1.1", optional=true}

[features]
default=["rocksdb", "memdb", "serde", "serde-json", "serde-rmp"]
rocksdb=["dep:rocksdb"]
# sqlite=["dep:rusqlite"]
memdb=["dep:dashmap"]

serde-json=["serde", "dep:serde_json"]
serde-rmp=["serde", "dep:rmp-serde"]
